In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
a1 = np.array([4,5,6,7,8])

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
a2 = np.array([3,4,3,2])

In [ ]:
a2

array([3, 4, 3, 2])

In [ ]:
a = np.concatenate((a1,a2))

In [ ]:
a

array([4, 5, 6, 7, 8, 3, 4, 3, 2])

In [ ]:
a1 = np.insert(a1,3,10)

In [ ]:
a1

array([ 4,  5,  6, 10,  7,  8])

In [ ]:

a1 = np.insert(a1,6,np.array([7,6,9]))

In [ ]:
a1

array([ 4,  5,  6, 10,  7,  8,  7,  6,  9])

In [ ]:
a1 = np.delete(a1,6)

In [ ]:
a1

array([ 4,  5,  6, 10,  7,  8,  6,  9])

In [ ]:
my_list = list(range(1,6))

In [ ]:
my_list

[1, 2, 3, 4, 5]

In [ ]:
a1 = np.arange(1,11)

In [ ]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a1 = np.arange(1,26,3)

In [ ]:
a1

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25])

In [ ]:
a1 = np.arange(40,7,-3)

In [ ]:
a1

array([40, 37, 34, 31, 28, 25, 22, 19, 16, 13, 10])

In [ ]:
x2 = list(a1)

In [ ]:
x2

[np.int64(40),
 np.int64(37),
 np.int64(34),
 np.int64(31),
 np.int64(28),
 np.int64(25),
 np.int64(22),
 np.int64(19),
 np.int64(16),
 np.int64(13),
 np.int64(10)]

In [ ]:
# list is just single dimensional
# while array could be multi-dimensional

In [ ]:
i = 34
a = i + x2[1]
print(a)

71


In [ ]:
a1 = np.array([3,6,5,8,6,4,3,2,8,7,8,9])
a1

array([3, 6, 5, 8, 6, 4, 3, 2, 8, 7, 8, 9])

In [ ]:
a2 = a1.reshape(3,4)    # two dimensional

In [ ]:
a2

array([[3, 6, 5, 8],
       [6, 4, 3, 2],
       [8, 7, 8, 9]])

In [ ]:
# array([[         two square brackets are means two dimensional array

#]])

In [ ]:
a3 = a1.reshape(3,2,2) # three dimensional arra    (read as 2*2 stacked on top with height of 3)

In [ ]:
a3

array([[[3, 6],
        [5, 8]],

       [[6, 4],
        [3, 2]],

       [[8, 7],
        [8, 9]]])

In [ ]:
k1 = [3,5,7,9]
k2 = [1,3,2,5]
k3 = [7,5,9,2]

k4 = np.array([k1,k2,k3])

In [ ]:
k4

array([[3, 5, 7, 9],
       [1, 3, 2, 5],
       [7, 5, 9, 2]])

In [ ]:
k4[1]

array([1, 3, 2, 5])

In [ ]:
k4[[1,2]]

array([[1, 3, 2, 5],
       [7, 5, 9, 2]])

In [ ]:
k4 [:,[1,3]]

array([[5, 9],
       [3, 5],
       [5, 2]])

In [ ]:
b = k4[:,1]

In [ ]:
b

array([5, 3, 5])

In [ ]:
b1 = b.reshape(-1,1)
b1

array([[5],
       [3],
       [5]])

In [ ]:
k4.flatten(order='c')

array([3, 5, 7, 9, 1, 3, 2, 5, 7, 5, 9, 2])

In [ ]:
k4.flatten(order='f')

array([3, 1, 7, 5, 3, 5, 7, 2, 9, 9, 5, 2])

In [ ]:
k4.transpose()

array([[3, 1, 7],
       [5, 3, 5],
       [7, 2, 9],
       [9, 5, 2]])

In [ ]:
newrow = np.array([1,5,7,6])

In [ ]:
a1 = np.vstack([k4, newrow])

In [ ]:
a1

array([[3, 5, 7, 9],
       [1, 3, 2, 5],
       [7, 5, 9, 2],
       [1, 5, 7, 6]])

In [ ]:
newcol = np.array([14,12,19])

In [ ]:
newcol

array([14, 12, 19])

In [ ]:
newcol = newcol.reshape(-1,1)

In [ ]:
newcol

array([[14],
       [12],
       [19]])

In [ ]:
a1 = np.hstack([k4, newcol])

In [ ]:
a1

array([[ 3,  5,  7,  9, 14],
       [ 1,  3,  2,  5, 12],
       [ 7,  5,  9,  2, 19]])

In [ ]:
a1 = a1.transpose()

In [ ]:
a1

array([[ 3,  1,  7],
       [ 5,  3,  5],
       [ 7,  2,  9],
       [ 9,  5,  2],
       [14, 12, 19]])

In [ ]:
a1 = np.insert(a1,2,[3,5,7], axis = 0)
a1

array([[ 3,  1,  7],
       [ 5,  3,  5],
       [ 3,  5,  7],
       [ 3,  5,  7],
       [ 7,  2,  9],
       [ 9,  5,  2],
       [14, 12, 19]])

In [ ]:
a1 = np.insert(a1,1,[3,5,7,1,3,4,1], axis = 1)
a1

array([[ 3,  3,  3,  1,  7],
       [ 5,  5,  5,  3,  5],
       [ 3,  7,  7,  5,  7],
       [ 3,  1,  1,  5,  7],
       [ 7,  3,  3,  2,  9],
       [ 9,  4,  4,  5,  2],
       [14,  1,  1, 12, 19]])

In [ ]:
np.delete(a1, (0,2), axis = 0)

array([[ 5,  5,  5,  3,  5],
       [ 3,  1,  1,  5,  7],
       [ 7,  3,  3,  2,  9],
       [ 9,  4,  4,  5,  2],
       [14,  1,  1, 12, 19]])

In [ ]:
np.delete(a1,(0,2), axis = 1)

array([[ 3,  1,  7],
       [ 5,  3,  5],
       [ 7,  5,  7],
       [ 1,  5,  7],
       [ 3,  2,  9],
       [ 4,  5,  2],
       [ 1, 12, 19]])

In [ ]:
# broadcasting in array

In [ ]:
a1 = a1+2      # add 2 in every element in array

In [ ]:
a1

array([[ 7,  7,  7,  5, 11],
       [ 9,  9,  9,  7,  9],
       [ 7, 11, 11,  9, 11],
       [ 7,  5,  5,  9, 11],
       [11,  7,  7,  6, 13],
       [13,  8,  8,  9,  6],
       [18,  5,  5, 16, 23]])

In [ ]:
a2 =  np.array([1,2,3,4,5,6,7])

In [ ]:
a1+a2           # column wise addition

array([[ 8,  9, 10,  9, 16],
       [10, 11, 12, 11, 14],
       [ 8, 13, 14, 13, 16],
       [ 8,  7,  8, 13, 16],
       [12,  9, 10, 10, 18],
       [14, 10, 11, 13, 11],
       [19,  7,  8, 20, 28]])

In [ ]:
a2 = a2.reshape(-1,1)

In [ ]:
a2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [ ]:
a1 + a2

array([[ 8,  8,  8,  6, 12],
       [11, 11, 11,  9, 11],
       [10, 14, 14, 12, 14],
       [11,  9,  9, 13, 15],
       [16, 12, 12, 11, 18],
       [19, 14, 14, 15, 12],
       [25, 12, 12, 23, 30]])

In [ ]:
b1 = np.array([1,2,3,4,5,6])

In [ ]:
b1 * 2

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
d1 = np.array([1,2,4,5,61])
d0 = np.repeat(d1,[1,2,3,4,5])


In [ ]:
d0

array([ 1,  2,  2,  4,  4,  4,  5,  5,  5,  5, 61, 61, 61, 61, 61])

In [ ]:
np.sort(d0)

array([ 1,  2,  2,  4,  4,  4,  5,  5,  5,  5, 61, 61, 61, 61, 61])

In [ ]:
np.sort(b1)[::-1]

array([6, 5, 4, 3, 2, 1])

In [ ]:
np.argsort(b1)

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.sort(a1, axis = 0)

array([[ 7,  5,  5,  5,  6],
       [ 7,  5,  5,  6,  9],
       [ 7,  7,  7,  7, 11],
       [ 9,  7,  7,  9, 11],
       [11,  8,  8,  9, 11],
       [13,  9,  9,  9, 13],
       [18, 11, 11, 16, 23]])

In [ ]:
b1 = np.array([12,1,41,1,5,11,14,])

In [ ]:
np.where(b1>=4)

(array([0, 2, 4, 5, 6]),)

In [ ]:
t1 = np.where(b1>4)

In [ ]:
len(t1)

1

In [ ]:
len(t1[0])

5

In [ ]:
b1[[1,3,5]]

array([ 1,  1, 11])

In [ ]:
len(np.where(b1>=4)[0])

5

In [ ]:
(b1>=4).sum()

np.int64(5)

In [166]:
t1

(array([0, 2, 4, 5, 6]),)

In [167]:
len(t1[0])

5

In [168]:
(a1>=4).sum()

np.int64(35)

In [175]:
np.unique(b1)

In [171]:
np.unique(b1, return_index=True)

(array([ 1,  5, 11, 12, 14, 41]), array([1, 4, 5, 0, 6, 2]))

In [173]:
np.unique(b1, return_counts=True)

(array([ 1,  5, 11, 12, 14, 41]), array([2, 1, 1, 1, 1, 1]))

In [174]:
np.unique(b1, return_inverse=True)          # for every unique element as reference from the unique elements we are just returning the index from the orignal b1

(array([ 1,  5, 11, 12, 14, 41]), array([3, 0, 5, 0, 1, 2, 4]))

In [2]:
import numpy as np
x1 = np.array([1,2,3,2,1])
x2 = np.array([1,2,6,5,6])


In [5]:
np.intersect1d(x1,x2)

array([1, 2])

In [7]:
np.union1d(x1,x2)

array([1, 2, 3, 5, 6])

In [10]:
np.setdiff1d(x2,x1)

array([5, 6])

In [13]:
x3 = np.array([4,10,2,5])

In [14]:
x3

array([ 4, 10,  2,  5])

In [15]:
x1

array([1, 2, 3, 2, 1])

In [16]:
np.in1d(x1,x3)

/tmp/ipython-input-2081356283.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(x1,x3)


array([False,  True, False,  True, False])

In [18]:
np.where(np.in1d(x1,x3))

/tmp/ipython-input-573868696.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.where(np.in1d(x1,x3))


(array([1, 3]),)

In [21]:
a1 = np.array([[1,4,7],[2,3,6]])

In [23]:
a1

array([[1, 4, 7],
       [2, 3, 6]])

In [25]:
a2  = np.array([[1,5],[0,2],[5,3]])

In [27]:
a2

array([[1, 5],
       [0, 2],
       [5, 3]])

In [29]:
a1.dot(a2)

array([[36, 34],
       [32, 34]])

In [30]:
np.matmul(a1,a2)

array([[36, 34],
       [32, 34]])

In [31]:
a3 = ([[1,2,3],[4,2,1],[3,2,6]])

In [32]:
a3

[[1, 2, 3], [4, 2, 1], [3, 2, 6]]

In [33]:
np.linalg.inv(a3)

array([[-0.38461538,  0.23076923,  0.15384615],
       [ 0.80769231,  0.11538462, -0.42307692],
       [-0.07692308, -0.15384615,  0.23076923]])

In [37]:
a3 = np.array([[1,2,3],[4,2,1],[3,2,6]])

In [38]:
a3

array([[1, 2, 3],
       [4, 2, 1],
       [3, 2, 6]])

In [58]:
from numpy import random

In [47]:
rd.rand(10)

array([0.40505545, 0.78583823, 0.51230245, 0.36251203, 0.59267987,
       0.37531339, 0.97881291, 0.16818771, 0.72117359, 0.11460994])

In [50]:
np.round(rd.rand(10),3)

array([0.6  , 0.715, 0.09 , 0.314, 0.368, 0.083, 0.218, 0.606, 0.442,
       0.462])

In [55]:
np.round(rd.rand(40),3)

array([0.201, 0.125, 0.083, 0.274, 0.74 , 0.249, 0.239, 0.459, 0.62 ,
       0.503, 0.39 , 0.577, 0.495, 0.234, 0.009, 0.162, 0.814, 0.885,
       0.362, 0.419, 0.872, 0.153, 0.441, 0.088, 0.557, 0.043, 0.709,
       0.329, 0.708, 0.054, 0.787, 0.945, 0.114, 0.828, 0.648, 0.198,
       0.908, 0.065, 0.748, 0.919])

In [56]:
numbers_between_10_and_40 = np.arange(10, 41)
print(numbers_between_10_and_40)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40]


In [59]:
np.random.randint(20,50)

36

In [60]:
np.random.randint(20,50,10)

array([48, 35, 29, 22, 29, 31, 21, 28, 29, 22])

!(img)[https://softwarerecs.stackexchange.com/questions/62286/visualizing-n-dimensional-arrays]

In [61]:
a1 = np.hstack([a1,g1])

NameError: name 'g1' is not defined