In [93]:
%%html
<link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:wght@300;400;500;600;700&display=swap" rel="stylesheet">

<style>
/* markdown + output */
body, .markdown-body, .jp-RenderedHTMLCommon, div.text_cell_render,
.notebook, .notebook * {
  font-family: "Source Serif 4", serif !important;
}

/* code editor (monaco) */
.monaco-editor, .monaco-editor * {
  font-family: "Source Serif 4", serif !important;
}
</style>

![image](https://media.geeksforgeeks.org/wp-content/uploads/20250222144920592095/stat.webp)

### Types of Data

`Continuous` 
- Result of a measurement, Decimals are possible (true value can be fractional)  
- Requires an **instrument** to measure  

`Discrete`
- Result of a **count**  
- No decimals, whole numbers only  

`Categorical (Attribute / Qualitative)`
- Describes **qualities**, **categories**, **labels**, not numeric values  
- **Examples:** gender, color, brand, type of car, yes/no, low/medium/high  

    categorical data types:  
    - **Nominal** (no natural order) → color, city, fruit  
    - **Ordinal** (natural order exists) → rating scales, education level, ranking

### Descriptive statistics

In [2]:
import pandas as pd
import numpy as np
import warnings
import os

In [3]:
os.chdir(r'/Users/proxim/Desktop/CDAC-DBDA-coursework/08.advanced-analytics-stats')

In [4]:
df = pd.read_excel('data/CDAC_DataBook.xlsx', sheet_name='ERPData')

In [5]:
df.head()

,MaterialID,Location,Quantity
0,TMI-43T,MWH-4,34
1,AXCP-78,MWH-1,67
2,LXCV-21,MWH-2,27
3,AXCP-78,MWH-5,65
4,AXCP-78,MWH-4,36


In [6]:
df.describe()

,Quantity
count,50.000000
mean,57.700000
std,31.887078
min,10.000000
25%,34.000000
50%,54.500000
75%,74.000000
max,152.000000


In [7]:
np.unique(df.MaterialID)

array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
      dtype=object)

In [8]:
len(np.unique(df.MaterialID))

6

In [9]:
len(df.MaterialID)

50

In [10]:
np.unique(df.MaterialID, return_counts=True)

(array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
       dtype=object),
 array([11,  8,  5,  5,  6, 15]))

In [11]:
mat_count = df.MaterialID.value_counts().reset_index()

In [12]:
mat_count

,MaterialID,count
0,TMI-43T,15
1,AXCP-78,11
2,DDBN-89,8
3,SDRT-67,6
4,LXCV-21,5
5,GCVB-79,5


In [13]:
mat_count['prop'] = mat_count['count']/sum(mat_count['count'])*100

# This calculates the percentage (proportion) of each MaterialID's count out of the total count,
# and stores it in a new column 'prop'. Each value shows what percent of the total each MaterialID represents.

In [14]:
mat_count

,MaterialID,count,prop
0,TMI-43T,15,30.0
1,AXCP-78,11,22.0
2,DDBN-89,8,16.0
3,SDRT-67,6,12.0
4,LXCV-21,5,10.0
5,GCVB-79,5,10.0


In [15]:
grades = np.array(['A','B','C'])

In [16]:
grades

array(['A', 'B', 'C'], dtype='<U1')

In [17]:
df = pd.read_excel('data/covid_cases.xlsx')

In [18]:
df.head()

,State,Cases
0,UP,250
1,KA,350
2,MH,650
3,KL,400
4,MP,350


In [19]:
df = df.sort_values('Cases', ascending=False)

In [20]:
df.head()

,State,Cases
2,MH,650
3,KL,400
1,KA,350
4,MP,350
0,UP,250


In [21]:
df['prop'] = df ['Cases']/sum(df['Cases'])*100

In [22]:
df.head()

,State,Cases,prop
2,MH,650,27.083333
3,KL,400,16.666667
1,KA,350,14.583333
4,MP,350,14.583333
0,UP,250,10.416667


In [23]:
round(np.cumsum(df.prop),2)

2     27.08
3     43.75
1     58.33
4     72.92
0     83.33
5     89.58
7     95.83
6    100.00
Name: prop, dtype: float64

In [24]:
np.cumsum(df.prop).iloc[1]

np.float64(43.75)

---

#### Descriptive Statistics

##### Central Tendency

* **Mean** $\rightarrow$ average
* **Median** $\rightarrow$ sorted middle value      (if n is odd n+1/2)
* **Mode** $\rightarrow$ frequency

---

##### Variation or Dispersion

* `Range` $\rightarrow$  max val - min val
* `IQR` $\rightarrow$  middle 50% of data   


* `Variance` ($\sigma^2$ or $s^2$): $\rightarrow$ The average of the **squared** differences from the Mean.
    * Formula (Population): $\sigma^2 = \frac{\sum (x_i - \mu)^2}{N}$
    * Formula (Sample): $s^2 = \frac{\sum (x_i - \bar{x})^2}{n-1}$

* `Standard Deviation` ($\sigma$ or $s$)`: The square root of the variance. It is the most commonly used measure of spread and is expressed in the same units as the data.
    * Formula (Population): $\sigma = \sqrt{\frac{\sum (x_i - \mu)^2}{N}}$
    * Formula (Sample): $s = \sqrt{\frac{\sum (x_i - \bar{x})^2}{n-1}}$

---
* **Skewness** - measure of the **asymmetry** of the distribution about its mean.
* **Kurtosis** - measure of the **tailedness** and **peakedness** of the distribution. 
---

In [27]:
grades=np.array(['A','B','C','B','C','A','A','A','B','C','A','A','A','B'])

In [28]:
np.unique(grades,return_counts=True)

(array(['A', 'B', 'C'], dtype='<U1'), array([7, 4, 3]))

In [29]:
p1=np.array([8,3,3])

In [30]:
np.cumsum(p1)     # sum of previous number and number itselt 

array([ 8, 11, 14])

In [31]:
np.unique(grades,return_counts=True)[1]

array([7, 4, 3])

In [32]:
df = pd.read_excel('data/CDAC_DataBook.xlsx', sheet_name='faithful')

In [33]:
df.head()

,eruptions,waiting
0,3.600,79
1,1.800,54
2,3.333,74
3,2.283,62
4,4.533,85


In [34]:
erupt = df['eruptions']

In [35]:
len(erupt)

272

In [36]:
sum(erupt)

948.677

In [37]:
m = sum(erupt)/len(erupt)

In [38]:
m

3.487783088235294

In [39]:
np.mean(erupt)

np.float64(3.4877830882352936)

In [40]:
df.eruptions.mean()

np.float64(3.4877830882352936)

In [41]:
x1 = np.sort(erupt)

In [42]:
x1[135]

np.float64(4.0)

In [43]:
x1[136]

np.float64(4.0)

In [44]:
(x1[135] + x1[136])/2

np.float64(4.0)

In [45]:
np.median(erupt)

np.float64(4.0)

In [46]:
students = [20,35,15]
total_marks = [8,9,10]



In [47]:
nums = np.array([20,35,15])
marks = np.array([8,9,10])

In [48]:
sum(nums*marks)/sum(nums)

np.float64(8.928571428571429)

In [49]:
len(np.where(erupt==1.867)[0])

8

In [50]:
np.where(erupt==1.867)

(array([ 36,  92,  98, 105, 130, 203, 212, 220]),)

don't calcualate mean if the values are highly volatile, calculate median instead
median can be calculated at any situation

calculation graphs should prefer higher number of records like salary [1,2,3,4,3,1,2,90,91] -> so the graph should be favoring the less salary people in viz.

 - mode = most frequent element

per dataset there could be only 1 mean and 1 median, but modes could be more (bimodal, multimodal)

In [51]:
np.ptp(erupt)                                       # calculate range inbuild

np.float64(3.4999999999999996)

In [ ]:
max(erupt)-min(erupt)                               # calculate range manual

# note - range shouldn't be used if the dataset is with extreme values 

3.4999999999999996

In [53]:
# there should be consistency while using the range, lots of organizations have stopped using the range

x1 = [4,5,6,3,4,2,3,4,4,5,1,9] # -> range is 8
x2 = [6,6,6,6,6,6,6,6,6,6,1,9] # -> range is 8 


# here in both cases the range is 8 but the x2 is more consistent


In [54]:
np.percentile(erupt,40)


np.float64(3.6)

In [55]:
np.percentile(erupt,40)
np.percentile(erupt,80)

np.float64(4.533)

In [56]:
max(erupt)

5.1

#### manual vs inbuilt method to calculate percentile, and understand percentile

In [57]:
t1=[1,1,2,2,3,3,3,3,4,4,4,4,4,4,5,5,5,5,5,6,6,6,6,6,7,7,7,7,7,7]

In [58]:
1 + (len(t1)-1) * 0.25

8.25

In [59]:
3 * 0.25 + 4 * 0.75

3.75

In [60]:
np.percentile(t1,25)

np.float64(3.25)

In [61]:
3 * 0.75 + 4* 0.25

3.25

In [62]:
1 + (len(t1)-1) * 0.7

21.299999999999997

In [63]:
t1[20]

6

In [64]:
t1[21]

6

In [65]:
1 + (len(t1) + 1) * 0.8

25.8

In [66]:
t1[23]

6

In [67]:
t1[24]

7

In [68]:
df.head()

,eruptions,waiting
0,3.600,79
1,1.800,54
2,3.333,74
3,2.283,62
4,4.533,85


In [69]:
df.describe()

,eruptions,waiting
count,272.000000,272.000000
mean,3.487783,70.897059
std,1.141371,13.594974
min,1.600000,43.000000
25%,2.162750,58.000000
50%,4.000000,76.000000
75%,4.454250,82.000000
max,5.100000,96.000000


In [70]:
np.percentile(erupt, 75) - np.percentile(erupt, 25)

np.float64(2.2915)

In [71]:
np.percentile(x2, 75) - np.percentile(x2, 25)

np.float64(0.0)

In [72]:
x2

[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 9]

In [73]:
np.var(erupt)        #population variance

np.float64(1.2979388904492861)

In [74]:
np.var(erupt, ddof=1)    # sample variance

np.float64(1.302728332849468)

In [75]:
np.std(erupt)             # population standard variance

np.float64(1.139271210225768)

In [76]:
np.std(erupt, ddof=1)      # sample standard deviation

np.float64(1.141371251105208)

In [77]:
len(erupt - np.mean(erupt))

272

In [78]:
sum(erupt - np.mean(erupt))

1.4854784069484595e-13

In [79]:
ss = sum((erupt - np.mean(erupt))**2)  # sum of squared deviation from mean

In [80]:
ss/len(erupt)

1.2979388904492863

In [81]:
np.var(erupt)

np.float64(1.2979388904492861)

In [82]:
(ss/len(erupt) ** 0.5)

21.406156563677587

In [83]:
np.std(erupt)

np.float64(1.139271210225768)

In [84]:
ss/(len(erupt)-1)

1.3027283328494683

In [85]:
np.var(erupt, ddof=1)

np.float64(1.302728332849468)

In [86]:
ss/(len(erupt)-1) ** 0.5

21.445614950277655