In [1]:
%%html
<link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:wght@300;400;500;600;700&display=swap" rel="stylesheet">

<style>
/* markdown + output */
body, .markdown-body, .jp-RenderedHTMLCommon, div.text_cell_render,
.notebook, .notebook * {
  font-family: "Source Serif 4", serif !important;
}

/* code editor (monaco) */
.monaco-editor, .monaco-editor * {
  font-family: "Source Serif 4", serif !important;
}
</style>


#### **NumPy Cheat Sheet — Most Used Functions**

####  Creating arrays
| Function | Purpose |
|---------|---------|
| np.array([...]) | Create array |
| np.arange(start, stop, step) | Range array |
| np.linspace(start, stop, num) | Evenly spaced numbers |
| np.zeros((rows, cols)) | Zero matrix |
| np.ones((rows, cols)) | One matrix |
| np.eye(n) | Identity matrix |

---

####  Random numbers
| Function | Purpose |
|---------|---------|
| np.random.rand(n) | Uniform random (0–1) |
| np.random.randn(n) | Normal distribution |
| np.random.randint(a, b, size) | Random integers |
| np.random.normal(loc, scale, size) | Normal distribution |

---

####  Array operations
| Function | Purpose |
|---------|---------|
| np.sum() | Sum |
| np.mean() | Mean |
| np.median() | Median |
| np.std() | Standard deviation |
| np.var() | Variance |
| np.min(), np.max() | Min/Max |
| np.sort() | Sort array |
| np.unique() | Unique values |
| np.argmax(), np.argmin() | Index of max/min |

---

####  Linear algebra
| Function | Purpose |
|---------|---------|
| np.dot(A, B) | Matrix multiplication |
| np.matmul(A, B) | Same as dot |
| np.linalg.inv(A) | Inverse |
| np.linalg.det(A) | Determinant |
| np.linalg.eig(A) | Eigenvalues & eigenvectors |

---

####  Reshaping & stacking
| Function | Purpose |
|---------|---------|
| arr.reshape(r, c) | Reshape array |
| np.hstack([a, b]) | Horizontal stack |
| np.vstack([a, b]) | Vertical stack |
| np.concatenate([a, b]) | Append arrays |

---

####  Logical & conditional
| Function | Purpose |
|---------|---------|
| np.where(cond) | Filter values |
| np.any(), np.all() | Check conditions |
| arr > 5 | Boolean array |

---

####  Math functions
| Function | Purpose |
|---------|---------|
| np.sqrt() | Square root |
| np.exp() | Exponential |
| np.log() | Natural log |
| np.power(a, b) | a^b |

---

### Pandas vs NumPy — When to Use What

| Task | Use Pandas | Use NumPy |
|------|-------------|------------|
| DataFrame (rows/columns) | ✔ | ✖ |
| Labeled data | ✔ | ✖ |
| Missing values | ✔ | ✖ |
| Fast math operations | ✔ | ✔✔✔ |
| Big matrix calculations | ✖ | ✔ |
| EDA & cleaning | ✔ | ✖ |

---

# Quick Memory Trick

**Pandas = tables with labels**  
**NumPy = fast number crunching**

---

In [368]:
import os
os.chdir(r'/Users/proxim/Desktop/CDAC-DBDA-coursework/08.advanced-analytics-stats')

In [369]:
import numpy as np

In [370]:
import pandas as pd

![img](https://i.sstatic.net/Tbe9W.png)

In [371]:
a1 = np.array([4,5,6,7,8])

In [372]:
type(a1)

numpy.ndarray

In [373]:
a2 = np.array([3,4,3,2])

In [374]:
a2

array([3, 4, 3, 2])

In [375]:
a = np.concatenate((a1,a2))

In [376]:
a

array([4, 5, 6, 7, 8, 3, 4, 3, 2])

In [377]:
a1 = np.insert(a1,3,10)

In [378]:
a1

array([ 4,  5,  6, 10,  7,  8])

In [379]:

a1 = np.insert(a1,6,np.array([7,6,9]))

In [380]:
a1

array([ 4,  5,  6, 10,  7,  8,  7,  6,  9])

In [381]:
a1 = np.delete(a1,6)

In [382]:
a1

array([ 4,  5,  6, 10,  7,  8,  6,  9])

In [383]:
my_list = list(range(1,6))

In [384]:
my_list

[1, 2, 3, 4, 5]

In [385]:
a1 = np.arange(1,11)

In [386]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [387]:
a1 = np.arange(1,26,3)

In [388]:
a1

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25])

In [389]:
a1 = np.arange(40,7,-3)

In [390]:
a1

array([40, 37, 34, 31, 28, 25, 22, 19, 16, 13, 10])

In [391]:
x2 = list(a1)

In [392]:
x2

[np.int64(40),
 np.int64(37),
 np.int64(34),
 np.int64(31),
 np.int64(28),
 np.int64(25),
 np.int64(22),
 np.int64(19),
 np.int64(16),
 np.int64(13),
 np.int64(10)]

In [393]:
# list is just single dimensional
# while array could be multi-dimensional

In [394]:
i = 34
a = i + x2[1]
print(a)

71


In [395]:
a1 = np.array([3,6,5,8,6,4,3,2,8,7,8,9])
a1

array([3, 6, 5, 8, 6, 4, 3, 2, 8, 7, 8, 9])

In [396]:
a2 = a1.reshape(3,4)    # two dimensional

In [397]:
a2

array([[3, 6, 5, 8],
       [6, 4, 3, 2],
       [8, 7, 8, 9]])

In [398]:
# array([[         two square brackets are means two dimensional array

#]])

In [399]:
a3 = a1.reshape(3,2,2) # three dimensional arra    (read as 2*2 stacked on top with height of 3)

In [400]:
a3

array([[[3, 6],
        [5, 8]],

       [[6, 4],
        [3, 2]],

       [[8, 7],
        [8, 9]]])

In [401]:
k1 = [3,5,7,9]
k2 = [1,3,2,5]
k3 = [7,5,9,2]

k4 = np.array([k1,k2,k3])

In [402]:
k4

array([[3, 5, 7, 9],
       [1, 3, 2, 5],
       [7, 5, 9, 2]])

In [403]:
k4[1]

array([1, 3, 2, 5])

In [404]:
k4[[1,2]]

array([[1, 3, 2, 5],
       [7, 5, 9, 2]])

In [405]:
k4 [:,[1,3]]

array([[5, 9],
       [3, 5],
       [5, 2]])

In [406]:
b = k4[:,1]

In [407]:
b

array([5, 3, 5])

In [408]:
b1 = b.reshape(-1,1)
b1

array([[5],
       [3],
       [5]])

In [409]:
k4.flatten(order='c')

array([3, 5, 7, 9, 1, 3, 2, 5, 7, 5, 9, 2])

In [410]:
k4.flatten(order='f')

array([3, 1, 7, 5, 3, 5, 7, 2, 9, 9, 5, 2])

In [411]:
k4.transpose()

array([[3, 1, 7],
       [5, 3, 5],
       [7, 2, 9],
       [9, 5, 2]])

In [412]:
newrow = np.array([1,5,7,6])

In [413]:
a1 = np.vstack([k4, newrow])

In [414]:
a1

array([[3, 5, 7, 9],
       [1, 3, 2, 5],
       [7, 5, 9, 2],
       [1, 5, 7, 6]])

In [415]:
newcol = np.array([14,12,19])

In [416]:
newcol

array([14, 12, 19])

In [417]:
newcol = newcol.reshape(-1,1)

In [418]:
newcol

array([[14],
       [12],
       [19]])

In [419]:
a1 = np.hstack([k4, newcol])

In [420]:
a1

array([[ 3,  5,  7,  9, 14],
       [ 1,  3,  2,  5, 12],
       [ 7,  5,  9,  2, 19]])

In [421]:
a1 = a1.transpose()

In [422]:
a1

array([[ 3,  1,  7],
       [ 5,  3,  5],
       [ 7,  2,  9],
       [ 9,  5,  2],
       [14, 12, 19]])

In [423]:
a1 = np.insert(a1,2,[3,5,7], axis = 0)
a1

array([[ 3,  1,  7],
       [ 5,  3,  5],
       [ 3,  5,  7],
       [ 7,  2,  9],
       [ 9,  5,  2],
       [14, 12, 19]])

In [424]:
# Insert a column with one value per row (a1 has 6 rows). The original list had 7 items causing a shape mismatch.
a1 = np.insert(a1, 1, [3, 5, 7, 1, 3, 4], axis=1)
a1

array([[ 3,  3,  1,  7],
       [ 5,  5,  3,  5],
       [ 3,  7,  5,  7],
       [ 7,  1,  2,  9],
       [ 9,  3,  5,  2],
       [14,  4, 12, 19]])

In [425]:
np.delete(a1, (0,2), axis = 0)

array([[ 5,  5,  3,  5],
       [ 7,  1,  2,  9],
       [ 9,  3,  5,  2],
       [14,  4, 12, 19]])

In [426]:
np.delete(a1,(0,2), axis = 1)

array([[ 3,  7],
       [ 5,  5],
       [ 7,  7],
       [ 1,  9],
       [ 3,  2],
       [ 4, 19]])

In [427]:
# broadcasting in array

In [428]:
a1 = a1+2      # add 2 in every element in array

In [429]:
a1

array([[ 5,  5,  3,  9],
       [ 7,  7,  5,  7],
       [ 5,  9,  7,  9],
       [ 9,  3,  4, 11],
       [11,  5,  7,  4],
       [16,  6, 14, 21]])

In [430]:
a2 =  np.array([1,2,3,4,5,6,7])

In [431]:
# column wise addition — ensure a2 length matches a1 rows
a1 + a2[:a1.shape[0]].reshape(-1,1)

array([[ 6,  6,  4, 10],
       [ 9,  9,  7,  9],
       [ 8, 12, 10, 12],
       [13,  7,  8, 15],
       [16, 10, 12,  9],
       [22, 12, 20, 27]])

In [432]:
a2 = a2.reshape(-1,1)

In [433]:
a2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [434]:
b1 = np.array([1,2,3,4,5,6])

In [435]:
b1 * 2

array([ 2,  4,  6,  8, 10, 12])

In [436]:
d1 = np.array([1,2,4,5,61])
d0 = np.repeat(d1,[1,2,3,4,5])


In [437]:
d0

array([ 1,  2,  2,  4,  4,  4,  5,  5,  5,  5, 61, 61, 61, 61, 61])

In [438]:
np.sort(d0)

array([ 1,  2,  2,  4,  4,  4,  5,  5,  5,  5, 61, 61, 61, 61, 61])

In [439]:
np.sort(b1)[::-1]

array([6, 5, 4, 3, 2, 1])

In [440]:
np.argsort(b1)

array([0, 1, 2, 3, 4, 5])

In [441]:
np.sort(a1, axis = 0)

array([[ 5,  3,  3,  4],
       [ 5,  5,  4,  7],
       [ 7,  5,  5,  9],
       [ 9,  6,  7,  9],
       [11,  7,  7, 11],
       [16,  9, 14, 21]])

In [442]:
b1 = np.array([12,1,41,1,5,11,14,])

In [443]:
np.where(b1>=4)

(array([0, 2, 4, 5, 6]),)

In [444]:
t1 = np.where(b1>4)

In [445]:
len(t1)

1

In [446]:
len(t1[0])

5

In [447]:
b1[[1,3,5]]

array([ 1,  1, 11])

In [448]:
len(np.where(b1>=4)[0])

5

In [449]:
(b1>=4).sum()

np.int64(5)

In [450]:
t1

(array([0, 2, 4, 5, 6]),)

In [451]:
len(t1[0])

5

In [452]:
(a1>=4).sum()

np.int64(22)

In [453]:
np.unique(b1)

array([ 1,  5, 11, 12, 14, 41])

In [454]:
np.unique(b1, return_index=True)

(array([ 1,  5, 11, 12, 14, 41]), array([1, 4, 5, 0, 6, 2]))

In [455]:
np.unique(b1, return_counts=True)

(array([ 1,  5, 11, 12, 14, 41]), array([2, 1, 1, 1, 1, 1]))

In [456]:
np.unique(b1, return_inverse=True)          # for every unique element as reference from the unique elements we are just returning the index from the orignal b1

(array([ 1,  5, 11, 12, 14, 41]), array([3, 0, 5, 0, 1, 2, 4]))

In [457]:
import numpy as np
x1 = np.array([1,2,3,2,1])
x2 = np.array([1,2,6,5,6])


In [458]:
np.intersect1d(x1,x2)

array([1, 2])

In [459]:
np.union1d(x1,x2)

array([1, 2, 3, 5, 6])

In [460]:
np.setdiff1d(x2,x1)

array([5, 6])

In [461]:
x3 = np.array([4,10,2,5])

In [462]:
x3

array([ 4, 10,  2,  5])

In [463]:
x1

array([1, 2, 3, 2, 1])

In [464]:
np.in1d(x1,x3)

/var/folders/57/62f2rv1j4w94h8tfp_c43b1c0000gn/T/ipykernel_61606/2081356283.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(x1,x3)


array([False,  True, False,  True, False])

In [465]:
np.where(np.in1d(x1,x3))

/var/folders/57/62f2rv1j4w94h8tfp_c43b1c0000gn/T/ipykernel_61606/573868696.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.where(np.in1d(x1,x3))


(array([1, 3]),)

In [466]:
a1 = np.array([[1,4,7],[2,3,6]])

In [467]:
a1

array([[1, 4, 7],
       [2, 3, 6]])

In [468]:
a2  = np.array([[1,5],[0,2],[5,3]])

In [469]:
a2

array([[1, 5],
       [0, 2],
       [5, 3]])

In [470]:
a1.dot(a2)

array([[36, 34],
       [32, 34]])

In [471]:
np.matmul(a1,a2)

array([[36, 34],
       [32, 34]])

In [472]:
a3 = ([[1,2,3],[4,2,1],[3,2,6]])

In [473]:
a3

[[1, 2, 3], [4, 2, 1], [3, 2, 6]]

In [474]:
np.linalg.inv(a3)

array([[-0.38461538,  0.23076923,  0.15384615],
       [ 0.80769231,  0.11538462, -0.42307692],
       [-0.07692308, -0.15384615,  0.23076923]])

In [475]:
a3 = np.array([[1,2,3],[4,2,1],[3,2,6]])

In [476]:
a3

array([[1, 2, 3],
       [4, 2, 1],
       [3, 2, 6]])

In [477]:
from numpy import random as rd

In [478]:
rd.rand(10)

array([0.01181205, 0.93165956, 0.30563537, 0.18504695, 0.04156519,
       0.45092734, 0.51552185, 0.88986211, 0.96440635, 0.09142884])

In [479]:
np.round(rd.rand(10),3)

array([0.834, 0.333, 0.473, 0.004, 0.564, 0.462, 0.045, 0.225, 0.133,
       0.793])

In [480]:
np.round(rd.rand(40),3)

array([0.242, 0.589, 0.213, 0.14 , 0.156, 0.448, 0.288, 0.563, 0.408,
       0.504, 0.833, 0.405, 0.559, 0.083, 0.408, 0.903, 0.687, 0.034,
       0.079, 0.614, 0.315, 0.467, 0.57 , 0.573, 0.631, 0.666, 0.972,
       0.194, 0.802, 0.804, 0.887, 0.723, 0.894, 0.503, 0.655, 0.434,
       0.02 , 0.904, 0.969, 0.219])

In [481]:
numbers_between_10_and_40 = np.arange(10, 41)
print(numbers_between_10_and_40)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40]


In [482]:
np.random.randint(20,50)

43

In [483]:
np.random.randint(20,50,10)

array([35, 45, 21, 28, 22, 43, 24, 21, 23, 42])